cd C:\Users\morri\Dropbox\Websites\ezcr

$rp = ".\tools\run_dropin.ps1"

$lines = @(
'[CmdletBinding()]'
'param('
'  [Parameter(Mandatory=$false)]'
'  [switch]$SkipGitCheckpoint,'
'  [Parameter(Mandatory=$false)]'
'  [switch]$SkipVerify'
')'
''
'Set-StrictMode -Version Latest'
'$ErrorActionPreference = "Stop"'
''
'function Write-Section([string]$Title) {'
'  Write-Host ""'
'  Write-Host ("==================== {0} ====================" -f $Title)'
'}'
''
'function Read-Json([string]$Path) {'
'  try { return (Get-Content -LiteralPath $Path -Raw | ConvertFrom-Json) } catch { return $null }'
'}'
''
'function Test-Command([string]$Name) { return $null -ne (Get-Command $Name -ErrorAction SilentlyContinue) }'
''
'function Get-RepoRootFromGit([string]$Fallback) {'
'  if (Test-Command "git") {'
'    try {'
'      $top = (git rev-parse --show-toplevel 2>$null).Trim()'
'      if ($top) { return $top }'
'    } catch {}'
'  }'
'  return $Fallback'
'}'
''
'Write-Section "LOAD CONFIG"'
'$scriptDir  = Split-Path -Parent $PSCommandPath'
'$configPath = Join-Path $scriptDir "dropin.config.json"'
'$config     = Read-Json $configPath'
'if (-not $config) { throw "Config load failed: $configPath" }'
''
'$RepoRoot = [string]$config.RepoRoot'
'if (-not $RepoRoot) { $RepoRoot = Resolve-Path (Join-Path $scriptDir "..") | Select-Object -ExpandProperty Path }'
'$RepoRoot = Get-RepoRootFromGit $RepoRoot'
''
'$ZipPath = [string]$config.ZipPath'
'if (-not $ZipPath) { throw "ZipPath missing in dropin.config.json" }'
'if (-not (Test-Path -LiteralPath $ZipPath)) { throw "Zip not found: $ZipPath" }'
''
'$ScratchDir = [string]$config.Scratch'
'if (-not $ScratchDir) { $ScratchDir = "C:\Temp\dropin_bundle_inspect" }'
'if (-not (Test-Path -LiteralPath $ScratchDir)) { New-Item -ItemType Directory -Path $ScratchDir -Force | Out-Null }'
''
'$BranchPrefix = [string]$config.Branch'
'if (-not $BranchPrefix) { $BranchPrefix = "chore/dropin" }'
''
'$ts = Get-Date -Format "yyyyMMdd_HHmmss"'
'$logPath = Join-Path "C:\Temp" ("dropin_" + $ts + ".log")'
''
'Write-Host "Config loaded: $configPath"'
'Write-Host "RepoRoot: $RepoRoot"'
'Write-Host "ZipPath:  $ZipPath"'
'Write-Host "Scratch:  $ScratchDir"'
'Write-Host "Branch:   $BranchPrefix"'
'Write-Host "SkipGitCheckpoint: $SkipGitCheckpoint"'
'Write-Host "SkipVerify:        $SkipVerify"'
''
'Write-Section "VALIDATE"'
'Write-Host "Log: $logPath"'
'Start-Transcript -Path $logPath -Force | Out-Null'
''
'try {'
'  Set-Location $RepoRoot'
''
'  if (-not $SkipGitCheckpoint) {'
'    Write-Section "GIT CHECKPOINT"'
'    if (-not (Test-Command "git")) { throw "git is not available in PATH." }'
'    $branchName = "$BranchPrefix-$ts"'
'    git checkout -b $branchName'
'  } else {'
'    Write-Section "GIT CHECKPOINT (SKIPPED)"'
'  }'
''
'  Write-Section "EXTRACT ZIP"'
'  Expand-Archive -Path $ZipPath -DestinationPath $ScratchDir -Force'
''
'  Write-Section "INSTALL"'
'  $repoInstaller = Join-Path $RepoRoot "tools\install_dropin.ps1"'
'  if (-not (Test-Path -LiteralPath $repoInstaller)) { throw "Missing tools\install_dropin.ps1." }'
''
'  $pwsh = (Get-Command pwsh -ErrorAction SilentlyContinue).Source'
'  if (-not $pwsh) { throw "pwsh not found in PATH." }'
''
'  & $pwsh -NoProfile -ExecutionPolicy Bypass -File $repoInstaller -ZipPath $ZipPath -RepoRoot $RepoRoot -ScratchDir $ScratchDir -LogPath $logPath'
'  if ($LASTEXITCODE -ne 0) { throw "install_dropin.ps1 failed with exit code $LASTEXITCODE" }'
''
'  if (-not $SkipVerify) {'
'    Write-Section "VERIFY"'
'    $repoVerify = Join-Path $RepoRoot "tools\verify_dropin.ps1"'
'    if (Test-Path -LiteralPath $repoVerify) {'
'      & $pwsh -NoProfile -ExecutionPolicy Bypass -File $repoVerify -RepoRoot $RepoRoot'
'      if ($LASTEXITCODE -ne 0) { throw "verify_dropin.ps1 failed with exit code $LASTEXITCODE" }'
'    } else {'
'      Write-Host "No verify script found; skipping."'
'    }'
'  } else {'
'    Write-Section "VERIFY (SKIPPED)"'
'  }'
''
'  Write-Section "DONE"'
'  Write-Host "Log file: $logPath"'
'  Write-Host "Scratch: $ScratchDir"'
'}'
'finally {'
'  Stop-Transcript | Out-Null'
'}'
)

Set-Content -LiteralPath $rp -Value $lines -Encoding UTF8
"Rewrote $rp (clean + parse-safe)."