-- ========================================
-- SEED KNOWLEDGE BASE WITH BUSINESS INFORMATION
-- ========================================
-- This seeds the knowledge base with essential business information
-- Embeddings will be generated by the API when this content is processed

DO $$
DECLARE
  ezcr_tenant_id UUID;
BEGIN
  -- Get tenant ID
  SELECT id INTO ezcr_tenant_id FROM tenants WHERE slug = 'ezcr-01';

  -- ========================================
  -- PRODUCT INFORMATION
  -- ========================================
  INSERT INTO knowledge_base (tenant_id, category, title, content, source) VALUES

  -- AUN250 Ramp
  (ezcr_tenant_id, 'product', 'AUN250 Folding Motorcycle Ramp Specifications',
   'The AUN250 is our heavy-duty folding motorcycle loading ramp. Key specifications: Weight capacity of 2,500 pounds, making it suitable for the heaviest touring bikes and adventure motorcycles. Constructed from aircraft-grade aluminum with a powder-coated finish. Features a non-slip surface for maximum traction. Folds in half for easy storage and transport. Dimensions when unfolded: 90 inches long x 12 inches wide. Weight: 45 pounds. Made in USA. Lifetime warranty included. Price: $1,299.',
   'manual'),

  -- AUN210 Ramp
  (ezcr_tenant_id, 'product', 'AUN210 Standard Motorcycle Ramp Specifications',
   'The AUN210 is our standard folding motorcycle loading ramp. Key specifications: Weight capacity of 2,000 pounds, suitable for most sport bikes, cruisers, and standard motorcycles. Constructed from high-grade aluminum. Features a non-slip surface. Folds in half for convenient storage. Dimensions when unfolded: 84 inches long x 12 inches wide. Weight: 38 pounds. Made in USA. Lifetime warranty included. Price: $999. Great value for riders with lighter motorcycles.',
   'manual'),

  -- Extensions
  (ezcr_tenant_id, 'product', 'AC001 Extension System Overview',
   'Our AC001 extension system adjusts the ramp angle for different vehicle heights. We offer three versions: AC001-1 for heights 35-42 inches ($149), AC001-2 for heights 43-51 inches ($249), and AC001-3 for heights 52-60 inches ($349). Each extension is made from the same aircraft-grade aluminum as our ramps and includes mounting hardware. Extensions are essential for safely loading motorcycles into taller vehicles like lifted trucks or high-bed trailers.',
   'manual'),

  -- ========================================
  -- INSTALLATION & USAGE
  -- ========================================
  (ezcr_tenant_id, 'installation', 'How to Use Your Motorcycle Ramp Safely',
   'Safe ramp usage: 1) Always inspect the ramp before use for damage or wear. 2) Ensure the ramp is properly positioned with the wide end at the vehicle and narrow end on the ground. 3) Check that both sides of the ramp are evenly placed. 4) Have a spotter assist you, especially for your first few uses. 5) Load the motorcycle slowly and steadily in first gear. 6) Keep your weight centered and maintain momentum. 7) Never attempt to load a motorcycle backwards down the ramp. 8) For unloading, back the motorcycle down slowly with a spotter.',
   'manual'),

  (ezcr_tenant_id, 'installation', 'Assembly Service and Demo Option',
   'We offer professional assembly service for $99, where our technician will assemble your ramp and demonstrate proper usage. Our premium Demo service ($149) includes assembly plus a comprehensive safety demonstration where we show you how to load and unload your motorcycle safely. This service is highly recommended for first-time users and is especially popular with customers aged 55+. Demo service is only available with pickup orders (not shipping). Both services include a detailed safety checklist and written instructions.',
   'manual'),

  (ezcr_tenant_id, 'installation', 'Boltless Tiedown Kit',
   'Our Boltless Tiedown Kit ($89) provides secure anchor points without drilling holes in your truck bed or trailer. The kit uses the existing stake pocket holes in truck beds for mounting. Includes four heavy-duty D-rings rated for 5,000 pounds each. Compatible with most pickup trucks manufactured after 1990. We highly recommend pairing this with our turnbuckle sets for the most secure motorcycle transport. Installation takes about 15 minutes with basic hand tools.',
   'manual'),

  -- ========================================
  -- SHIPPING & DELIVERY
  -- ========================================
  (ezcr_tenant_id, 'shipping', 'Shipping Information and Costs',
   'We offer two delivery options: Pickup (free) from our facility in [Location], or shipping ($185) via FedEx Ground. Shipping typically takes 3-5 business days within the continental US. We ship to all 48 contiguous states. Alaska and Hawaii shipping available at additional cost (contact us for quote). All shipments are insured and require signature upon delivery. Ramps are packaged securely in custom boxes to prevent damage during transit. Orders placed before 2 PM EST typically ship same day.',
   'manual'),

  (ezcr_tenant_id, 'shipping', 'Pickup Option Details',
   'Pickup is free and available during business hours: Monday-Friday 8 AM - 5 PM, Saturday 9 AM - 2 PM. Please call ahead (800-687-4410) to schedule your pickup time. This ensures your order is ready when you arrive. Pickup typically takes 10-15 minutes. If you select our Demo service, please allow 30-45 minutes for the demonstration. Our facility has ample parking for trucks and trailers.',
   'manual'),

  -- ========================================
  -- WARRANTY & RETURNS
  -- ========================================
  (ezcr_tenant_id, 'warranty', 'Lifetime Warranty Coverage',
   'All EZ Cycle Ramp products come with a lifetime warranty against defects in materials and workmanship. This warranty covers: structural failures, weld breaks, and material defects. The warranty does NOT cover: normal wear and tear, damage from misuse or abuse, modifications to the product, or cosmetic issues that don''t affect function. To file a warranty claim, contact us at 800-687-4410 with photos of the issue and your order number. We will repair or replace defective products at no charge.',
   'manual'),

  (ezcr_tenant_id, 'warranty', 'Return Policy',
   'We offer a 30-day money-back guarantee. If you''re not completely satisfied, return the product in its original condition within 30 days for a full refund (minus shipping costs). The product must be unused or lightly used with no damage. Customer is responsible for return shipping costs unless the product is defective. Refunds are processed within 5-7 business days of receiving the returned product. Customized or modified ramps cannot be returned. Contact customer service before returning to receive a Return Authorization (RA) number.',
   'manual'),

  -- ========================================
  -- FREQUENTLY ASKED QUESTIONS
  -- ========================================
  (ezcr_tenant_id, 'faq', 'What weight capacity do I need?',
   'For weight capacity, consider your motorcycle''s wet weight plus rider and any gear. Sport bikes typically weigh 400-500 lbs, cruisers 600-900 lbs, and touring bikes 800-1,000+ lbs. Our AUN210 (2,000 lb capacity) handles 99% of motorcycles. The AUN250 (2,500 lb capacity) is recommended for the heaviest touring bikes like Gold Wings, or if you plan to load two-up with passenger and full luggage. When in doubt, choose the higher capacity for peace of mind.',
   'manual'),

  (ezcr_tenant_id, 'faq', 'How do I measure my vehicle for the configurator?',
   'For pickup trucks: Measure your bed length with the tailgate CLOSED, then measure again with tailgate OPEN (this is your total length). Measure height from ground to the top edge of your closed tailgate. For vans: Measure from the back doors to the front of the cargo area. Measure height from ground to the cargo floor. For trailers: Measure the full bed length. Measure height from ground to the trailer bed. All measurements should be in inches. A helper and measuring tape are recommended for accuracy.',
   'manual'),

  (ezcr_tenant_id, 'faq', 'Which extension do I need?',
   'Your extension is determined by your load height (ground to cargo bed): 35-42 inches requires AC001-1, 43-51 inches requires AC001-2, and 52-60 inches requires AC001-3. If you''re between sizes, choose the next size up. Most standard pickup trucks (F-150, Silverado, Ram) fall in the 35-42 inch range and need AC001-1. Lifted trucks typically need AC001-2 or AC001-3. If you''re unsure, measure your height and call us at 800-687-4410 for personalized advice.',
   'manual'),

  (ezcr_tenant_id, 'faq', 'Do I need a cargo extension?',
   'A cargo extension is recommended if your total cargo length (bed with tailgate open) exceeds 80 inches. This provides a gentler loading angle and better stability. Most standard pickup trucks (60-70 inch beds) do NOT need a cargo extension. Long-bed trucks (8-foot beds = 96+ inches) typically do. The configurator will automatically recommend a cargo extension if needed based on your measurements.',
   'manual'),

  (ezcr_tenant_id, 'faq', 'What are turnbuckles and do I need them?',
   'Turnbuckles are heavy-duty tie-down straps that secure your motorcycle during transport. We offer them in pairs: one pair ($89) secures the front wheel, two pairs ($159) secures front and rear for maximum stability. They''re recommended for: long-distance transport, highway speeds, rough roads, and heavier motorcycles. If you have our Boltless Kit, turnbuckles are strongly recommended as they work together perfectly. Basic tiedown straps ($29) are also available for lighter-duty use.',
   'manual'),

  -- ========================================
  -- BUSINESS INFORMATION
  -- ========================================
  (ezcr_tenant_id, 'general', 'About EZ Cycle Ramp',
   'EZ Cycle Ramp has been manufacturing premium motorcycle loading ramps since [Year]. We specialize in heavy-duty, American-made ramps designed for safety and durability. All our products are manufactured in the USA using aircraft-grade aluminum. We serve thousands of motorcycle enthusiasts, from weekend riders to professional racers and dealerships. Our mission is to make motorcycle transport safe, easy, and reliable. Every ramp comes with our lifetime warranty and is backed by our expert customer service team.',
   'manual'),

  (ezcr_tenant_id, 'general', 'Contact Information and Hours',
   'Contact us: Phone: 800-687-4410 (toll-free), Email: support@ezcycleramp.com, Website: www.ezcycleramp.com. Business hours: Monday-Friday 8:00 AM - 6:00 PM EST, Saturday 9:00 AM - 2:00 PM EST, Closed Sundays and major holidays. For after-hours questions, email us and we''ll respond the next business day. Emergency pickup appointments can be arranged by calling ahead. We pride ourselves on responsive customer service and typically answer calls within 2 minutes during business hours.',
   'manual'),

  (ezcr_tenant_id, 'general', 'Payment Methods Accepted',
   'We accept all major credit cards (Visa, MasterCard, American Express, Discover), debit cards, PayPal, and Apple Pay. For business or fleet orders over $5,000, we also accept wire transfer and Net 30 terms (subject to credit approval). All transactions are processed securely through Stripe. We do not store credit card information on our servers. Sales tax is collected for orders shipped to [applicable states]. A 3% processing fee is added to all orders to cover payment processing costs.',
   'manual');

  -- Note: Embeddings will be generated by the embedding API endpoint
  -- See src/app/api/embeddings/generate/route.ts

END $$;
